apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
type: Opaque
stringData:
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  gemini-api-key: {{ .Values.secrets.geminiApiKey | quote }}
  auth-secret: {{ .Values.secrets.authSecret | quote }}
